"""add billing_events + fix download_tokens FKs

Revision ID: 94429fb1d069
Revises: ca1c06efe170
Create Date: 2025-10-04 12:13:43.335366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94429fb1d069'
down_revision = 'ca1c06efe170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('file_ids_json', sa.Text(), nullable=True),
    sa.Column('bytes_total', sa.Integer(), nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_user_id'), ['user_id'], unique=False)

    op.create_table('download_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_tokens_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_download_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_token_token_hash'))

    op.drop_table('download_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('issued_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_token_token_hash'), ['token_hash'], unique=1)

    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_download_tokens_file_id'))

    op.drop_table('download_tokens')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_user_id'))

    op.drop_table('billing_events')
    # ### end Alembic commands ###
