"""add file_share (RBAC)

Revision ID: c05d9ccd98e4
Revises: c26e872e629f
Create Date: 2025-09-16 14:58:52.520040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05d9ccd98e4'
down_revision = 'c26e872e629f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'shared_with_user_id', name='uq_file_share_file_user')
    )
    with op.batch_alter_table('file_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_share_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_share_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_share_shared_with_user_id'), ['shared_with_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_share_shared_with_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_share_owner_id'))
        batch_op.drop_index(batch_op.f('ix_file_share_file_id'))

    op.drop_table('file_share')
    # ### end Alembic commands ###
