"""add download_token table

Revision ID: c26e872e629f
Revises: c04b136097dd
Create Date: 2025-09-16 11:55:25.500375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26e872e629f'
down_revision = 'c04b136097dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_token_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_token_token_hash'))

    op.drop_table('download_token')
    # ### end Alembic commands ###
