"""add credits_delta to billing_events

Revision ID: c7fe9fd5eac7
Revises: 94429fb1d069
Create Date: 2025-10-05 16:55:47.927998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fe9fd5eac7'
down_revision = '94429fb1d069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_token_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_download_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_download_tokens_file_id')
        batch_op.drop_index('ix_download_tokens_token_hash')
        batch_op.drop_index('ix_download_tokens_user_id')

    op.drop_table('download_tokens')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits_delta', sa.Integer(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('credits_delta')

    op.create_table('download_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('file_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['encrypted_file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_download_tokens_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_download_tokens_token_hash', ['token_hash'], unique=1)
        batch_op.create_index('ix_download_tokens_file_id', ['file_id'], unique=False)

    with op.batch_alter_table('download_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_download_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_download_token_file_id'))

    op.drop_table('download_token')
    # ### end Alembic commands ###
