"""add credit_usage table

Revision ID: ca1c06efe170
Revises: 87f127b95185
Create Date: 2025-09-24 14:48:53.080063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1c06efe170'
down_revision = '87f127b95185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('bytes_total', sa.Integer(), nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_usage')
    # ### end Alembic commands ###
