"""add category to encrypted_file

Revision ID: e814a28d01ee
Revises: c05d9ccd98e4
Create Date: 2025-09-17 10:30:53.575368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e814a28d01ee'
down_revision = 'c05d9ccd98e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False))
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_encrypted_file_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypted_file_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_encrypted_file_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_encrypted_file_user_id'))
        batch_op.drop_index(batch_op.f('ix_encrypted_file_filename'))
        batch_op.drop_index(batch_op.f('ix_encrypted_file_category'))
        batch_op.alter_column('content_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
